### ISSUE TITLE
Better docs for GdnsdPluginApi

### ISSUE THREAD

**Issue by avb76** [gdnsd/gdnsd#105]
Hi,

Is there a way to have better docs for GdnsdPluginApi?

Thanks!

Cheers,
Gabriel

**Comment by blblack** [comment]
There's no real "guide" or good documentation.  The manpage is rambling (at best), and the best way to know what to do is to read the other plugins' code and/or the header files that are installed.  Sorry, I haven't made a big push to document it better for third party use primarily because the API is known to be relatively unstable and not the best design.  Something else to address in the long term if there's ever time :)
