### ISSUE TITLE
2.2.3 regression results in "Failed to disable DF bit for UDP socket: Protocol not available"

### ISSUE THREAD

**Issue by Southparkfan** [gdnsd/gdnsd#115]
When upgrading from 2.2.0 to 2.2.3, every restart fails with the error "Failed to disable DF bit for UDP socket: Protocol not available". Since @paravoid deleted the previous release from the Debian archive (I think this is common practice?), the only way to rollback was by using the 2.2.0 package from the apt cache.

Config available at https://github.com/miraheze/dns.

This error was reproduced on a Debian 8 VPS (using the stretch package) powered by OpenVZ virtualization.

**Comment by blblack** [comment]
I don't think there are any relevant changes from 2.2.0 to 2.2.3, at least not that I can see in the commit logs.  There's definitely been no network changes.  Really almost everything since 2.2.0 has been updates to plugin code, not to the core daemon (`src/` and `libgdnsd/`), so it's pretty easy to audit.  Even the few changes in the core code have mostly been trivial cleanups, with the exception of one complex bugfix related to the zonefile loader.  So without a doubt the most-perplexing question is why reverting to 2.2.0 fixes your issue at all, if that's the only change.

To dig a little deeper though: my suspicion is that this is IPv6 -related.  Try changing `listen` from `any` to `0.0.0.0` ?  I notice in your config link, you've already done that with `http_listen` for some reason...

**Comment by Southparkfan** [comment]
@blblack changing listen to 0.0.0.0 fixed the error, and GDNSD works again. So indeed seems to be IPv6 related.

I wonder what changed then (in gdnsd itself or the gdnsd package), and how this affects our IPv6 clients (because now only clients with IPv4 could access our sites?).

**Comment by blblack** [comment]
Well, there's some distinctions to draw here on IPv6 support and what it means:

1. Even if all your authdns servers only listen on IPv4, they can still hand out IPv6 response data (AAAA records), allowing IPv6 clients of your actual service to use IPv6.
2. The clients generally don't contact the authdns server directly, usually a cache does it on their behalf, so for DNS query purposes, what matters really isn't the IPv6 capabilities of the end-client, but the IPv6 capabilities of the caches they're using.
3. If you have AAAA records in the upstream glue for your domain's nameservers (or in your own data for your nameserver hostnames), those caches may try to reach you over IPv6 and fail if your listen is `0.0.0.0` (but they'll probably be smart and try ipv4 too).  If you don't, they were never going to try in the first place.

Does your VPS actually have working IPv6?  Do you have AAAA glue upstream of you in the DNS?

**Comment by blblack** [comment]
Note also, I see this for public info about OpenVZ + IPv6 in general: https://openvz.org/IPv6

**Comment by Southparkfan** [comment]
Yes, our DNS servers should have working IPv6:
```
root@misc1:~# ifconfig
[removed lo interface, unrelated]
venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: 2a00:d880:6:787::2/64 Scope:Global
          inet6 addr: 2a00:d880:6:787::3/64 Scope:Global
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:1231432845 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1134604120 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:259012959226 (241.2 GiB)  TX bytes:603575493301 (562.1 GiB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:185.52.1.76  P-t-P:185.52.1.76  Bcast:185.52.1.76  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

I tried a dig, which seems to work all fine:
```
root@vps1:~# dig miraheze.org @2a00:d880:6:787::2 | grep 'SERVER' -B 5

;; ADDITIONAL SECTION:
miraheze.org.           150     IN      AAAA    2a00:d880:5:569::2

;; Query time: 0 msec
;; SERVER: 2a00:d880:6:787::2#53(2a00:d880:6:787::2)
```

I don't know what an upstream glue is :-) I'll ask one of my colleagues when they're back (he might know it). Mind explaining a bit what you mean?

**Comment by blblack** [comment]
Upstream glue is what information the `.org` nameservers have about `miraheze.org` nameservers.  This is how DNS caches in the world find your authdns servers initially (and often, always):
```
bblack-mba:~ bblack$ dig @a0.org.afilias-nst.info. miraheze.org A
[...]
;; AUTHORITY SECTION:
miraheze.org.		86400	IN	NS	ns1.miraheze.org.
miraheze.org.		86400	IN	NS	ns2.miraheze.org.

;; ADDITIONAL SECTION:
ns1.miraheze.org.	86400	IN	A	192.184.82.120
ns1.miraheze.org.	86400	IN	AAAA	2604:180:0:ec::2
ns2.miraheze.org.	86400	IN	A	185.52.1.76
ns2.miraheze.org.	86400	IN	AAAA	2a00:d880:6:787::2
```

So, yes, your upstream glue has AAAA records, which means it's not great that your actual nameservers aren't listening on those IPv6 addresses, as other caches may try to use them to find information about your domain(s).  That information should be consistent between the upstream glue and what's actually being served by your servers for the same, in-bailiwick nameserver data, which it is:
```
bblack-mba:~ bblack$ dig @ns1.miraheze.org miraheze.org NS
[...]
;; ANSWER SECTION:
miraheze.org.		300	IN	NS	ns2.miraheze.org.
miraheze.org.		300	IN	NS	ns1.miraheze.org.

;; ADDITIONAL SECTION:
ns2.miraheze.org.	300	IN	A	185.52.1.76
ns2.miraheze.org.	300	IN	AAAA	2a00:d880:6:787::2
ns1.miraheze.org.	300	IN	A	192.184.82.120
ns1.miraheze.org.	300	IN	AAAA	2604:180:0:ec::2
```

So, you definitely need to either fix the IPv6 issues, or remove those IPv6 addresses for ns[12] from both your zonefiles and the upstream glue set via your domain registrar.

**Comment by blblack** [comment]
As for the error itself with `listen = any`, it should be coming from this line (since we know it's an IPv6 socket that emitted the error, because the listen hack fixed it):

https://github.com/gdnsd/gdnsd/blob/master/src/dnsio_udp.c#L141

So basically, that code is conditional on the headers defining `IPV6_DONTFRAG`, and yet when gdnsd attempts a setsockopt, it fails with an errno that indicates the protocol (IPv6) is not available at all.  This doesn't make basic sense, as by then we've already created an IPv6 socket (which we're now operating on), and we've also already successfully set at least one other IPv6 socket option `IPV6_V6ONLY`.

This whole issue is puzzling on its own (what about this OpenVZ environment makes the DF-disable fail for IPv6 with a "protocol not available"?), and additionally it's even more confusing that the behavior is inconsistent when the only difference is v2.2.0 vs v2.2.3.  I don't see anything remotely related in the changelogs for gdnsd itself or the debian packaging.

**Comment by Southparkfan** [comment]
@blblack thank you for the effort, it's very much appreciated.

I have the 2.2.0 package in the apt cache - perhaps there were more changes applied by the 2.2.3 upgrade than just GDNSD 2.2.0 -> GDNSD 2.2.3? My knowledge of debs, unpacking, differences, etc is all very limited, but I'm more than happy to upload the (which are now deleted from the debian apt repos) 2.2.0 deb so you can compare the differences between the two packages - if you think that would be useful.

Also please let me know if there is anything else that could be useful. I have no idea either why this happens, our IPv6 should be working fine (even on OpenVZ)...

**Comment by alanpearce** [comment]
I'm also running into this problem with 2.2.4 on an IPv6-only OpenVZ Debian container. I don't have 2.2.0 available, so I'm a bit stuck.

Anything I could do to help debug the issue?

**Comment by blblack** [comment]
This was fixed to just log an error rather than fail fatally in 2.3.0 onwards, in the commit above.  I still think that ultimately the issue lies in the OpenVZ environment, not in the gdnsd code.
