### ISSUE TITLE
Suggestion for template enhancement, add mtime and filename varibles

### ISSUE THREAD

**Issue by extremeshok** [gdnsd/gdnsd#118]
Basically when the template files are read by gdnsd assigns 2 variables for each template file (zone)

[mtime]   -> (mtime of the file)
[filename] -> (name of the file)

which are then applied to the template

It would allow for simplified management without having to manually increment the SOA serial and one can symlink a file and have the values apply on the fly. Yes I am aware this can be accomplished by user scripts and configuration utilities.

example template: sample.com

```
$TTL 3600
$ORIGIN [filename].
@  1D  IN SOA  xs1.nameserver.com.  admin.[filename].  (
  [mtime]  ; serial
  3600  ; refresh
  600  ; retry
  1209600  ; expire
  360  ; ncache
  )
@  3600  A    192.168.1.1
```

a symlink test.com to sample.com
would create a "virtual" template of the following

```
$TTL 3600
$ORIGIN test.com.
@  1D  IN SOA  xs1.nameserver.com.  admin.test.com.  (
   2147483647 ; serial
  3600  ; refresh
  600  ; retry
  1209600  ; expire
  360  ; ncache
  )
@  3600  A    192.168.1.1
```

"virtual" = in memory template

**Comment by blblack** [comment]
I don't really think there's much argument for internal templating in the general case as a feature.  There are hundreds of external tools and languages for templating zonefiles with.  We'd be reproducing that work poorly, yet again ( which is reminiscent of https://xkcd.com/927/ ).

On the specific tags here for the zone name and the serial:

**Zone name**

Seems pointless, as this is already available in the RFC standard stuff.  `@` is an alias for the zone name itself, and simply leaving off the trailing dot can append the zone name to any other name.  In gdnsd in particular, the `$ORIGIN` always starts out implicitly as the name of the zone (I think other servers do this too, but I don't know if it's explicitly in the standards off-hand).  Assuming no corner cases with strange filenames, which your template example would be broken on but the replacement would work on, your example:

```
$ORIGIN [filename].
@  1D  IN SOA  xs1.nameserver.com.  admin.[filename].  (
```

Could be done today with just:
```
@  1D  IN SOA  xs1.nameserver.com.  admin (
```

**Automatic Serial**

This one, I think, has some merit.  We can do this without true templates, just by defining a magic value for the SOA serial field (like `AUTO`) which generates the serial automagically.  I think there's a lot of open questions, though, about how we'd define those serial numbers and how useful they are.

The first thing to note is that, technically, since gdnsd doesn't support `AXFR` and similar, there's no pragmatic purpose to serials served by gdnsd.  At best they're a debugging tool for confirming which version of the data the server has loaded from the outside.  If you don't care about that external visibility for debugging/confirmation, you could just make all your serials the fixed value `1` and everything would work fine.  This has a twin effect: it means this whole thing isn't all that important, but it also gives us more wiggle room to do imperfect things with an automatic serial in this work if we need to.

So, design questions:

1. Portably, only full-second mtime resolution is available, yet it's entirely possible to have the file written to multiple times in a single second, and even reloaded correctly in full by gdnsd multiple times in a single second.  So we could see real updates to the data without any change of serial if we directly encoded 1-second mtimes.  Is that acceptable?

2. What's our format? `YYYYMMDDHHMMSS` has 12 digits, and the serial numbers in the DNS protocol have less than 10 digits of precision (max 2^31-1).  Dropping digits from our data means even worse precision problems than the 1-second mtime problem.  We could do some more-efficient encoding of the datestamp into an integer based on the constraints of the digits' values, but then it wouldn't necessarily be clear to humans what any serial means, other than the fact that it's different from some other value.

**Comment by blblack** [comment]
I think I've changed my mind about the zone name being a useful value in zonefiles in general (because it's the only way to allow back-tracking instead of append-only when you have tons of `$ORIGIN` sub-spaces).  Auto-SOA-serial still seems mildly useful but tricky to design right.  Will look at all this again during 3.x dev.

**Comment by blblack** [comment]
I did end up implementing an auto-serial on the way to 3.x, and then ended up reverting it.  It's always tempting and sounds useful, but in practice it's not: 565b61c09a32199e73a5c8d68048148b4a8f5591
