### ISSUE TITLE
http status is really unusable since upgrade from 1.x to 2.x

### ISSUE THREAD

**Issue by alter** [gdnsd/gdnsd#124]
gdnsd 1+:
{
"service": "some-pool-eu-ie/ipv4/somewebserver-gce-eu-9/webserver_30s",
"state": "UP"
},
gdnsd 2+:
{
"service": "44.36.16.14/webserver_30s",
"state": "UP",
"real_state": "UP"
},

In the 1+ version we understood pool name and servername, in the 2+ version we don't know both of them.

Please make a configuration option for choosing http status style.

**Comment by blblack** [comment]
In both versions, monitored services are de-duplicated when referenced by multiple resources.  In 1.x, the service was described arbitrarily with the data from the first resource that referenced it (and "first" wasn't very well-defined in some cases), whereas in 2.x only the unique attributes of what's being monitored are in the description, not the (possibly multiple) resources that make use of the monitored data.

The description (e.g. `44.36.16.14/webserver_30s`) is not arbitrary; it's also used to match entries in admin_state for administrative state override, and thus it's good that it's fixed in the face of changes to the set of consuming resources, or else inconsistencies on certain types of configuration update would arise.  The schema is also shared with virtual resources (such as geoip per-datacenter entries).  Arguably the internal name of the field (`desc`), should instead be something like (`key`), but that's not really relevant to the end-user point of view.

What we could do is add the set of consuming resources as additional metadata automatically.  It would probably be a comma-separated string in HTTP or an array in JSON, as in:
```
{
   "service": "44.36.16.14/webserver_30s",
    "state": "UP",
    "real_state": "UP",
    "consumers": [
        "some-pool-eu-ie/ipv4/somewebserver-gce-eu-9",
        "something else"
    ]
},
```

**Comment by allanjude** [comment]
What I miss is being able to tell if 'all servers in some-pool-eu-ie', are down. There used to be a top level up/down state for each 'data center'. We used this to trigger spawning more instances

**Comment by blblack** [comment]
This situation hasn't really evolved for 3.0 (sorry!), but keeping this complaint around for when all the plugin-related things get refactored/rewritten in the Future.

**Comment by allanjude** [comment]
Thanks

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
