### ISSUE TITLE
Reload config without restarting gdnsd?

### ISSUE THREAD

**Issue by hippoking** [gdnsd/gdnsd#132]
Hello,

I've been testing Gdnsd for 2 weeks and it's amazing.

Zone files changes can be scanned automatically, however is there a way to reload config without restarting gdnsd? Because I need to change geo info frequently.

Thanks in advance!
Best,
XT

**Comment by allanjude** [comment]
+1

**Comment by blblack** [comment]
This has been asked on the mailing list before as well, I think.  gdnsd doesn't currently have a generic mechanism for a config reload without restarting the daemon (because parts of the configuration are used in the expensive pre-generation of a lot of static things).

However, since many many versions ago, gdnsd has had low-impact, overlapped restarts for config reload.  The idea there was that a whole new daemon with new config could nearly-completely bring itself online (including listening sockets via SO_REUSEPORT) and then take over from the old daemon, with the lost requests capped down to basically "whatever might have been lost in the UDP recv buffers at the moment of switching").  This solution is relatively simple in code complexity terms and was good enough to be the answer, IMHO.

However, systemd broke the mechanisms used for these overlapped restarts by implying its own new constraints on the subject of daemon management.  If gdnsd is running as a systemd service/unit, the overlapped restarts don't work anymore.

I suspect probably everyone who's raising this issue lately is suffering from the systemd breakage.  On a non-systemd system, "/usr/sbin/gdnsd restart" (or similar invoked by the init script) does the overlapped restart behavior.

There's a branch I haven't worked on in a while ( https://github.com/blblack/gdnsd/tree/mcp ) which substantially refactors the daemon and adds a ton of complexity in the name of having a proper overlapped restart mechanism that works around systemd's brain damage, but it's not quite finished yet, sorry.  Mostly what slows me down is I hate the amount of complexity I'm being forced to add there, it's a nightmare.  I may still try to find a better way to structure around these issues.

Relatedly, the latest systemds have also started binding 127.0.0.1:53 by default for a local dns resolver, which will break default startup of any authserver whose default configuration binds 0.0.0.0:53 :(.  Many versions ago "interface scanning" was gdnsd's norm and would have worked around this easily, but long ago I began deprecating that in favor of listening on the ANY address, specifically because it was supposedly going to make life easier under systemd...

**Comment by hippoking** [comment]
Thanks!

**Comment by blblack** [comment]
Closing this up as a WONTFIX, as gdnsd will continue to effectively require a restart for configuration changes.  The upcoming gdnsd-3.x prototypes support even better seamless overlapped restarts than we had in the past (hypothetically, zero requests lost), and they work for the systemd case as well.  That branch is still a WIP (current prototype is https://github.com/blblack/gdnsd/tree/3.x-prototype8), but expected first release is "Sometime in 2018", and then we won't have to explain why smooth restarts fail to work under the (common) systemd case anymore.
