### ISSUE TITLE
Installation resources

### ISSUE THREAD

**Issue by hsafe** [gdnsd/gdnsd#139]
Hi,
I seem not to find anywhere how to install the package from source...:(
Is there a wiki and howto for that? unfortunately the web has been poor to provide it either...
In my scenario I want to compile the gdnsd in CentOS7 + the API ...
Appreciate to guide me where to look if already a doc or how to achieve if not...

Thanks a lot

**Comment by nblount** [comment]
I know it is a long time since this was posted but I have been fighting with this today.

Install the following packages some may not be required but these are what I installed:
ragel, libtool, libev-devel, libmaxminddb-devel, autoconf, automake, make, gcc, perl, libunwind-devel

Get liburcu and install (URL in gdnsd INSTALL file)

Assuming we now have all the components you can run this from gdnsd source directory:
libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure

At this point it fails because ragel on CentOS 7 is version 7 not 6 so edit the configure file and find where it mentions "Compiler version 6" and replace the 6 with 7 then re-run configure.

make
make install

You should have it installed under /usr/local/ now.

**Comment by hsafe** [comment]
Hi
Thanks nblount...Ill test and hopefully works ...will post the results...
