### ISSUE TITLE
auto_dc_limit doesn't seem to work

### ISSUE THREAD

**Issue by cstdenis** [gdnsd/gdnsd#143]
I have auto_dc_limit set to the default 3

When I use gdnsd_geoip_test, it correctly shows the 3 closest datacenters.

However when I do an actual query, it only returns the IPs from the closest datacenter, not the 3 closest.

**Comment by blblack** [comment]
This is the intended behavior.  `auto_dc_limit` limits the length of the list of DCs the automatic distance-mapping code will generate (as you've observed in `gdnsd_geoip_test`), but the geoip code always returns only one DC's addresses for a given query (the closest one that's not `DOWN` due to monitored state or `admin_state`).
