### ISSUE TITLE
map excluding one or more DCs

### ISSUE THREAD

**Issue by lucasRolff** [gdnsd/gdnsd#144]
Hi,

This is a minor question

Let's say I have a map containing a total of 20 datacenters, spread around the world - is there a possibility whenever I do a DYNA entry in the zone file to target the map like DYNA geoip!global - but then say exclude a list of datacenters for a given DYNA record - such as ams, nyc and sin

The reason why I want to do this, is to make a list of selective datacenters for each individual record (being based on geoip plugin) - so a domain can get assigned let's say, only ams DC, or ams, fra, nyc, lax

I could create different maps with every possible combination, but afaik, that would become 400 maps which is a bit overkill.

**Comment by blblack** [comment]
I think this is now possible as of v2.3.0 and higher by setting the plugin-level attribute `undefined_datacenters_ok => true`.  Instead of defining up to 400 maps, you'll need to define up to 400 resources referencing the same map, and then a resource can define IPs for a given subset of all of the map's datacenters.  This avoids, at least, the costs of loading 400 separate maps.

Note that there are no protections against bad configuration combinations when this attribute is used.  It is also possible for map entries (automatic from coordinates, or manual based on e.g. country) to list less than all datacenters.  If both map entries and some resources are missing various datacenters from their respective lists, it's possible to create a configuration such that certain client networks resolve certain resources to "no answers".

Concretely:
* a map might have a total datacenter list `[a, b, c, d, e]`.
* a map might contain network lookups defined like: `192.0.2.0/24 => [a, b, c]` (note that lists with less-than-all-dcs like this can also be generated for you when using the automatic coordinate-based mode of operation).
* a resource referencing this map might only define addresses for `[d, e]`.
* A user in `192.0.2.0/24` looking up a name using the above resource would get no useful answer, and this case is not explicitly prevented or warned about.

I think `undefined_datacenters_ok` is about as far as we'll go in this direction in 2.x.  Everything about related things will change in new and exciting ways for 3.x :)

**Comment by lucasRolff** [comment]
Hi Brandon,

that indeed sounds like a possible solution, maintaining 400 resources shouldn't be too bad, and I think it indeed will have a lot lower memory footprint than the map thing.

99.99% of the time I use the automatic coordinate-based mode - the only time I'd actually specify a subnet manually is whenever some ISP ends up with all their subnets at wrong coordinates (sadly happened a few times, but then later fixed in a new geoip DB).

I'll look forward to 3.x - but I'd guess there's quite some time for that release  👍 

Thanks for your reply!
