### ISSUE TITLE
anyone tried a lot of domains?

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#162]
Hi,

I have 0.2M domains if use gdnsd Will it work well?

Because gdnsd is based on file storage zone files, This is what I worry about 0.2M file in a folder like Loading speed, etc.
Memory is not a problem, I have a lot of memory available

thanks

**Comment by holinhot** [comment]
I have add 0.3M zone test
root@45:/etc/gdnsd/zones# ls -l|grep "^-"| wc -l
324284
root@45:/etc/gdnsd/zones#

looks like work will. just run gdnsd checkconf slowly

**Comment by blblack** [comment]
In general, the code doesn't have any arbitrary restrictions on domain counts, and tends to scale decently on memory usage per domain.  It would be interesting to note how long the checkconf (or startup) takes in these cases on reasonable server hardware, as I haven't tested timing on such things in a long time.  Zonefile-loading is currently single-threaded, which is something that could be improved down the road perhaps as well to make the timing better.

Upcoming plans for the 3.x may impact such cases, though...  One of the current features in 2.x is the ability for gdnsd to asynchronously reload any of your hundreds of thousands of zones on the fly at runtime when it changes on-disk using `zones_rfc1035_auto`, without reloading the all the other zonefiles that didn't change.  This feature was implemented with large zonefile counts in mind, but it has turned out to be a mis-feature for many other use-cases, where treating the entire set of all zonefiles as a single transactional update would be preferable (e.g. for error-checking, and for consistency of cross-zone references, and to be able to sanely support `$INCLUDE`, etc).  So far the preliminary work for 3.x has eliminated the `zones_rfc1035_auto` functionality and not replaced it.

If the load times for large zone datasets are problematic, we could potentially revisit this, but my  suspicion so far is we're better leaving out the per-file autoloading's complexity and limitations, and that the load times for reasonable zonefile counts (e.g. up to ~1M) shouldn't be too horribly awful.  If the collective update rate exceeded the speed limits imposed by the time-to-reload, one could always ratelimit the updates (e.g. pool up zonefile changes and reload zone data only once per 5 minutes), or with such large counts, multiple independent sets of authservers splitting up the domain set probably isn't a bad idea either.

**Comment by blblack** [comment]
@extremeshok Can you give me a better idea what the requirement for zones_rfc1035_auto is for your domain provisioning?  Is it about the time-to-reload with many domains vs loading a single?  I suspect that in most reasonable scenarios, a full reload-zones after dropping provisioning changes into place should perform reasonably, but perhaps I'm wrong.  gdnsd doesn't currently support `$include` at all, and the main reason is it's difficult (but not impossible!) to support it correctly with `zones_rfc1035_auto`.

**Comment by blblack** [comment]
For reference, I've done a few rough benchmarks.  These are with a build of the 3.x prototype code on my old 2012 MacBook Air running Debian Stretch.  Three types of zonefile are attempted at various counts:

* _tiny_ which is a ~500B file with just 1xSOA + 3xNS
* _small_ which is a ~2KB file with just a few normal records like a small public zone (~20 RRs total: SOA, NS, MX, a few A/AAAA, some TXT records for DKIM, various commentary lines, etc)
* _huge_ which is a ~200KB file with a complex mix of ~4K RRs (taken from a live infrastructure zone at wikimedia).

Many copies of one of these files are made at many randomized domainnames in the zones directory, then load time is tested with checkconf:

filetype | count | wallclock time
-----------|---------|--------
tiny | 10K | ~0.25s
tiny | 100K | ~2.5s
small | 10K | ~0.47s
small | 100K | ~4.2s
huge | 100 | ~0.38s
huge | 1K | ~3.7s
huge | 10K | ~59s (but ~39s user+sys, rest was iowait and swapping, etc) 

For _tiny_ and _small_ zonefiles, the scaling seems fairly linear and within reason up to ~100K zones.  For the _huge_ testcase, probably reasonable at least up to a few thousand?  Wallclock linearity broke down in the _huge_ 10K case, but that seems to be about my old laptop's hardware limitations when dealing with a ~2GB set of zonefiles when it only has ~4GB total RAM, rather than gdnsd itself.

Taking this laptop-based worst case and looking at the 1K huge dataset: in order for the reloads to actually overlap/delay on each other, you'd have to have a net rate of reloading your zone data ~16 times per minute to run into issues.  Or thinking more in terms of a bunch of independent zonefiles with independent sources and rates of update, a long-term average reload rate in excess of ~1 data change per hour per zonefile, each triggering an independent reload of all the zones.  Obviously as you approach those limits, you could simply have the scripts/programs that are managing your data updates coalesce multiple updates into a single reload as well.  Keep in mind zone data reloads are seamless (they don't interrupt live service).

We could speed them up by parallelizing the loading of the zonefiles with multiple threads fairly easily, but I don't know that most would want that tradeoff, as it would just tie up more hardware CPUs that could be answering requests quickly instead.  There's doubtless some efficiency to go after in the loading code in general (cleaning up the data structures, more-efficient strictness checking of the data, etc).  Better hardware on a real server machine probably does much better than these benchmark runs anyways.

**Comment by holinhot** [comment]
Yes, I tried use a SSD will be faster But sometime use a HDD, running service gdnsd start will have a error systemctl timout, I think the gdnsd.service have a default timeout value Eventually failed to start

**Comment by blblack** [comment]
Closing this idle thread for now, but I'd be ok with picking this thread back up as a fresh feature request for the two obvious directions we could go for speeding up large datasets: parallelization over multiple CPU cores, and/or mtime-based optimizations to not reload unchanged zones.
