### ISSUE TITLE
any idea to support Rate Limit

### ISSUE THREAD

**Issue by louishot** [gdnsd/gdnsd#163]
hi,

This can limit the speed of ip reply.

It can reduce DNS amplification attacks

**Comment by blblack** [comment]
Issue #36 talks about the standard RRL mechanism for mitigating amplification attacks, which hasn't yet been implemented (although at one point someone uploaded a pull request with an implementation, then withdrew the code before I ever had a chance to look at it).

In general though, I tend to see it as a low priority issue for gdnsd's case for a few reasons:

*  It's basically impossible to usefully limit amplification via RRL without doing careful manual per-site configuration tuning to minimize the negative impact on legitimate client requests.  Even with such tuning, it's impossible to completely eliminate the harm to legitimate client requests.
* The main driver of the DNS Amplification scares in recent years has been DNSSEC, as DNSSEC has much larger response packets than the traditional DNS.  gdnsd doesn't implement DNSSEC, and thus doesn't suffer from this exacerbation of the issue.
* Lacking DNSSEC, generally the next-best target for DNS Amplification is ANY-queries, as they tend to return the largest non-DNSSEC response packets.  gdnsd has mitigated this specific case without a ratelimiter from v2.3.0 onwards, by introducing a new option `any_mitigation` which defaults to being turned on.  With the option on, UDP ANY queries are always answered with a truncation response (no useful amplification), forcing the client to retry over TCP if they really wanted the results.  Because ANY-queries are primarily used for testing, debugging, and research, this is deemed a reasonable mitigation in terms of legitimate client impact.

**Comment by blblack** [comment]
I'm basically rejecting RRL at the design level at this time.  I think we will eventually implement DNSSEC, but in a way that minimizes amplification issues appropriately.  I also don't like the tradeoffs with RRL in general (it's hard to implement it in a way that's both useful and avoids collateral damage to legitimate requests, and requires a lot of state-tracking about clients).  We've already implemented RFC 8482 as well, which eliminates ANY-queries as reflection sources in general.
