### ISSUE TITLE
Update gdnsd-monitor check to use http/1.1 or http/2.0

### ISSUE THREAD

**Issue by paladox** [gdnsd/gdnsd#167]
Hi, gdnsd-monitor should be updated to use http/1.1 rather then http/1.0.

It should use http/2.0 if a user uses https and the server supports http/2.0

**Comment by blblack** [comment]
Given it doesn't persist connections or do anything else fancy, and does send a `Host` header, there's basically no distinction between http/1.0 and http/1.1 in practice (except in the case that the server fails to support http/1.0 at all? Are there such servers now?  Note it does parse an HTTP/1.1 response to a 1.0 request).

As for http/2.0 and/or TLS... that's a ton of complexity to drag into the monitoring plugin.  It might make more sense to use `extmon` or `extfile` driving something like `curl` to do HTTPS+http/2 healthchecks.  

In general, in the longer term, I think I'm moving more in that direction: push monitoring to external stuff with a decent interface for importing states, rather than expand on the existing plugins.  It may be a while (like 4.x timeframe, and 3.x isn't even quite out yet), but eventually I think I'll probably get rid of monitoring plugins entirely (other than external interfaces like extmon/extfile, as non-plugins), and re-abstract resolver plugins to a more-limited scope as well (to just do the abstract mapping part, rather than deal with addresses directly).
