### ISSUE TITLE
Gdnsd configuration over TCP

### ISSUE THREAD

**Issue by dlemper** [gdnsd/gdnsd#179]
Hi,
I recently switched from nsd to gdnsd/3.0. This was done in order to cover my current use case: allow certbot to add a dns record for lets encrypt dns validation.
The challenge for me is to do this using seperate docker container, one for gdnsd and one for certbot.
With gdnsd 3.x there is the control tool gdnsdctl, which uses unix domain sockets to update the configuration.

My question is: can I switch from unix domain sockets to tcp for configuration?

Then I could use a docker network for communication between certbots container and gdnsd container. That‘s more reliablr than sharing a unix domain socket.

Thank you in advance!

**Comment by blblack** [comment]
There's not currently any support in gdnsd for doing control stuff over TCP, sorry!  Most of the commands could in theory be done over TCP.  The only real exception is the private inter-daemon stuff that happens during daemon replacement (because it uses FD passing).

I think it's probably a decent feature to add, although it will have to come with some warnings about the security of the TCP socket.  Maybe by default it would support just read-only commands, and require config to explicitly enable the true "control" commands like acme-challenge, stop, reload-zones, replace.  I can see some real ease-of-use cases for supporting it even in the non-container world.

In the present, the best workaround is probably the volume mount stuff.  I assume you've already seen it, but for anyone else reading this in the meantime, there are some ugly workarounds that involve mounting a host volume inside both containers to hold the unix socket (in gdnsd's case, you'd want the volume mount to end up being the rundir), e.g. https://www.jujens.eu/posts/en/2017/Feb/15/docker-unix-socket/ and other google-able examples.

**Comment by blblack** [comment]
While I was starting at this: there's another possibly simpler workaround too, which is to launch `socat` in the background in both containers to forward control socket connections over TCP, and do a minimal gdnsd config in the certbot container to let `gdnsdctl` find the new socket path.  Something like:

In the gdnsd container:
```
socat tcp4-listen:1234,fork unix-client:/run/gdnsd/control.sock &
```

In the certbot container, assuming `192.0.2.1` is the IP it can reach the gdnsd container at:
```
mkdir -p /tmp/gdnsd/etc /tmp/gdnsd/run
echo "options = { run_dir = /tmp/gdnsd/run }" >/tmp/gdnsd/etc/config
socat unix-listen:/tmp/gdnsd/run/control.sock,fork tcp4-connect:192.0.2.1:1234 &
```

And then the certbot container should be able to successfully run commands like:
```
gdnsdctl -c /tmp/gdnsd/etc acme-challenge ...
```

Obviously as reference earlier, there's security implications to exposing the unix socket over TCP, so make sure nefarious things can't connect to it!

**Comment by dlemper** [comment]
Sounds like you want to implement this, great! :)

I already thought about socat, but then I need a software that watches socat and gdnsd if both are running.. (I want the container to die if the software crashes for whatever reason) Nevertheless its good to see, that you also thought about this ;)

Another idea was: I can write a small rest service that watches for gdnsd and can execute gdnsdctl when it gets a json with the needed information for the acme challenge.

Oh and about your security concerns: you‘re absolutely right, the socket must be save! I rely on docker networks for this, so certbot and gdnsd get their own network and nobody else can use that network. (If someone breaks into one of these containers or breaks into the host system, I‘ll get much bigger problems for sure..)

**Comment by dlemper** [comment]
I wrote a simple node service, that creates a small REST api for the gdnsdctl commands: https://github.com/dlemper/gdnsdctl-rest

The service starts gdnsd and stops itself, if gdnsd stops. The API is available on port 3000 and you can access 'stats' for example by using 'curl http://localhost:3000/stats' (if the service runs on localhost).
I have to add some documentation to the sources...

**Comment by blblack** [comment]
Awesome, nice work :)  I'm uploading a patch to master shortly for `gdnsdctl` directly over TCP as well, which will make its way into 3.1.x releases.

**Comment by blblack** [comment]
@dlemper - I noticed your gdnsdctl-rest seemed to have a use-case for remote stop, whereas in the native TCP gdnsdctl stuff, I left stop out of the list of control commands available over TCP (kind of arbitrarily, but my thinking at the time is that if you stop over TCP, there's no way to re-start over TCP, and whatever has a mechanism to re-start the daemon surely has other ways to execute the stop).  Do you think stop should be allowed over the native TCP stuff?  Does it make your use-case easier? I could go either way myself.

**Comment by dlemper** [comment]
Actually, I just implemented every command from gdnsctl as a rest endpoint, but I only need the acme challenge commands myself. So, for me it doesn‘t matter, however your point is a good one and I‘d leave ‚stop‘ out, too.

**Comment by blblack** [comment]
Releasee with 3.1.0!
