### ISSUE TITLE
Return zone reload on filesystem monitoring

### ISSUE THREAD

**Issue by sunnybear** [gdnsd/gdnsd#187]
Hello. Thank you for great product. We were happy with v2, but there was no GeoIPv2 support. Switched to v3. And noticed that there is no zone auto-update with files.
Auto zone reload was very useful to auto-update every zone on multi-zone server on just updating zone file (not with every DNS daemon explicit zone-reload after zone file update). Please return this functionality.

**Comment by blblack** [comment]
Can you describe your use-case or how you integrate/push your zone data updates?  Is the problem a performance one (cost of reloading many zones), or a functional one (no way to tell the daemon to reload after updating the files)?

Rambly explanatory post:

Obviously, at one point in this past I thought this was a good feature as well.  The design idea behind it was that a DNS server and its directory of zonefiles could/should operate much like you'd expect from a simple HTTP server and its directory of HTML files.  You just change the files and the network output changes, which has a nice simplicity to it.

However, there were a few different design and implementation problems with this notion:

1) **Implementing it sanely and without corner-case issues turns out to be very complex**.  Among the many issues one has to hack around: filesystem timestamps aren't perfect, a lot of potential zonefile-writing software doesn't use atomic filesystem operations correctly (or can't, in the case of multiple related updates to separate zonefiles), there are multiple possible representations of a zone's name leading to multiple zonefiles for the same zone to decide between (e.g. upper vs lower case), the whole device or filesystem can be remapped from underneath you, etc.  These were all hacked-around successfully with various sorts of hacks like quiescence timers and re-checks, but it creates hundreds of lines of very very complicated and fragile code to maintain, and even then, there are still ways the user and/or other software can do enough Bad Things to confuse it into a bad state.

2) **Most users of this software for critical production zones would disable it anyways** - We certainly did at Wikimedia.  We have deployment software which controls the deployment of zone data updates, and we wanted that software to be in explicit control of the process by issuing the reload command when warranted, because deploying with the automatic reloads can cause races where different nameservers reload different partial updates.  For example, a given commit to our DNS repository might touch the data of 23 zonefiles in a related way (e.g. changing a CNAME and the destination it points at in another zone).  The first server might notice the filesystem update with only the first 3 files changed, and the next gets all 23 in one go, etc... and these temporary inconsistencies can cause user-visible failures of resolution in some cases, depending on the nature of the change.  I'll grant that, for most cases, making such racy updates is still bad (due to cache TTLs and the necessary asynchronicity of updating multiple authservers), but there are cases where these races make it worse than it otherwise would be.

3) **It prevented any reasonable implementation of `$INCLUDE`** - Having a working `$INCLUDE` turned out to be really hard under all the constraints of (1) while also supporting automatic per-file reloads.  It might have been tractable in some sense, but it was just a bridge too far.  Imagine all the scenarios in which one has to backtrack from deeply-nested includes to decide which zonefiles to reload, and the more-direct data races between fs update notifications from multiple files in a nested chain of `$INCLUDE`, some of which might alter which files are included, etc.

At the end of the day, you're going to have some script or other piece of software involved in updating the zone files themselves anyways, and so it's pretty trivial to just add a `gdnsdctl reload-zones` to the end of it to trigger the reload.  So, from a functional perspective, it seems fine to me to require such a thing.

The primary legitimate pain point I expect with this change is the performance one.  If you have literally thousands of zonefiles, 2.x had the ability to reload singular files quickly instead of waiting long times to reload the entire dataset on every change from a slow, spinny disk.  This is really an independent issue from the automatic filesystem change detection, but the two are intertwined, and the new explicit-only reload-zones happens to always reload all the files together.

I've added one feature to partially alleviate this for some users: the new parameter `zones_rfc1035_threads`, which can be set to a higher value (default 2) to allow the parsing of zonefiles on reload to use multiple parallel threads.  The usefulness of this setting will vary depending on your scenario (how slow the disk is, how large and/or complex and/or numerous the zonefiles are), but it can help in some scenarios where reading the raw data and parsing it are the key slowdowns.  Obviously, using SSDs (which are cheap and plentiful these days) or even a tmpfs to store the zone data directory gdnsd reads from can help a lot as well.

What's still on the radar is to bring back a much simpler form of filesystem checking which can skip reloading individual zones when they (and all `$INCLUDE` dependencies) haven't changed since the last time they were loaded.  This would probably bring back most of the missing performance for those "thousands of tiny zones, only a few updated at a time" cases, and is pretty easily doable.  It would probably be default-off feature that the user has to enable explicitly, as it has some costs of its own (e.g. cloning all the extant zone data at the start of the operation, etc).  I'm waiting to design and implement this until I've gotten some other core changes done, though, in case it ends up interacting badly with that work (the final refactor of how DYNx and plugins and monitoring works, which is mostly going to foist it off to external tooling/scripts, and the first drafts of DNSSEC design work).

**Comment by blblack** [comment]
Sorry for the slow responses, and that this isn't meeting your needs!

As a workaround for now, there are some simple CLI things you could run (I guess wrap them up as a running service daemon via initscript/systemd?) on each server to emulate the old behavior.

For instance, this bash snippet which uses inotifywait from inotify-tools:

`inotifywait -m /etc/gdnsd/zones/ | while read x; do while read -t 3 x; do :; done; gdnsdctl reload-zones; done`

Or in expanded/clearer form:

```
inotifywait -m /etc/gdnsd/zones/ | while read x; do
    while read -t 3 x; do
        :        
    done
    gdnsdctl reload-zones
done
```

This will cause a reload on any inotify-detected changes to the zonefiles, but since inotify events can be spammy (even updating a single file can spam out multiple inotify-level events, and then there's the odds your rsync job updates several zonefiles rapidly), the nested read construct waits to fire the reload command until the stream of filesystem event notifications has a full 3 seconds timeout (may want to tweak this) with no new output, which should under normal conditions give what you're looking for: a reload once per rsync execution which actually updates data in the zones directory.

**Comment by sunnybear** [comment]
Thank you. But I don't want to make one more inotify-service around changing files - just to reload zones. We need also to monitor all services (in case of any fault - restart), start these service on server start, add to ansible with new edge deployment, etc, etc. We don't need additional service just to look after zones' changes on DNS edges. gdnsd 2.x is quite good with this.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)

**Comment by sunnybear** [comment]
thank you for the great product
