### ISSUE TITLE
Reloads in a post-pidfile world

### ISSUE THREAD

**Issue by ppaeps** [gdnsd/gdnsd#211]
I upgraded from gdnsd2 to gdnsd3 this week.  While this was largely uneventful, the automation was a little upset about gdnsd3 no longer writing a pidfile.

In the previous world order, the automation did something like this:

```
if [ ! -f .failed ]; then
  if [ -f /var/run/gdnsd/gdnsd.pid ]; then
    if [ /var/run/gdnsd/gdnsd.pid -ot config -o  /var/run/gdnsd/gdnsd.pid -ot zones/geo.freebsd.org ]; then
      service gdnsd configtest || ( touch .failed; exit 1)
      service gdnsd restart || ( touch .failed; exit 1)
    fi
  fi
fi
```

As far as I can tell, with gdnsd3, there is no way to determine whether the configuration changed since the last (successful) reload.  Other things I tried:

* `gdnsdctl stats`: the value of "uptime" does not reset after `gdnsdctl replace`
* `stat /var/run/gdnsd/control.sock`: the mtime of the control socket does not change after `gdnsdctl replace`

I could teach our init script to write a pidfile but that feels like a fragile hack.

Would you accept a patch that makes gdnsd manage a pidfile again?  Or is there a better way to do this?

**Comment by blblack** [comment]
> As far as I can tell, with gdnsd3, there is no way to determine whether the configuration changed since the last (successful) reload. Other things I tried:

Yeah, I'd agree it doesn't currently offer any deterministic mechanism for this at present.  Of course, once you really drill down into any such mechanism (e.g. pidfile timestamps or tracking PID numbers in general), it's almost impossible to eliminate all corner case modes of failure, including in the automation scripts themselves.  

In terms of explaining gdnsd3's existing philosophy on related bits: it's hoped that by sticking to gdnsdctl (or, raw control sock) interfaces, there's some measure of reliability.  The daemon controlsock and gdnsdctl code go to great lengths in the name of reliability and determinism (that the command's return value reliably indicates that it actually executed the user's intent successfully).  So, for example, writing new config data (or zone data, or a new daemon binary) to the filesystem (and ensuring those writes are synced!) and then executing `gdnsdctl replace` and having it return zero should reliably mean that those filesystem changes are in effect for the running service.  These mechanisms are even designed to do so in the face of competing actors (e.g. multiple independent administrators, cronjobs, and other automation mechanisms executing colliding gdnsdctl commands  - e.g. the zone reloader script can execute `gdnsdctl reload-zones` without thinking much about whether the independently-operated config reload script is also executing `gdnsdctl replace` at the same time, or even more than one actor executing independent overlapping `replace` operations, so long as everything completes within overall timeout constraints!).  Failures of either can happen and may need to be retried (gdnsdctl does some retrying on its own in some collision cases, within the given overall timeout), but success retvals always should mean real success.

[Aside - you mentioned in an email having observed `replace` failures and not trusting it - even if you don't have the time to really debug this, just sending in the logs from the operation might help me pin it down.  The two daemon instances produce fairly detailed syslog output that can pinpoint where things went off the rails.  It's been pretty rock-solid for us, but I don't have a lot of pragmatic experience with it on FreeBSD, so there could be something unique going on that I hadn't thought of!]

The root of your issue here, which is definitely true, is that gdnsd doesn't really expose any metadata that can answer the automation/admin's question "Has the currently-running daemon been alive since before time X (when I wrote a config update to the filesystem)?".

I think it's totally reasonable to want that metadata, I just hadn't seen the need for it given how our model works at my $work.  What our automation does is basically pull config and zones from a git repo to a staging area on the DNS hosts, run a config check against that staging area's copy, then have the automation diff the staging copy against the live copy to decide things like "have important files changed?", then overwrite the live copy with the new data, then execute `replace` or `reload-zones` commands when they're necessary based on the earlier diff.  This still leaves many holes where things could go wrong with low probability.  An example is that if you don't log and complain about the final operation failing in some way that wasn't caught by the staging config check and allow the system-as-a-whole to carry on silently, the mechanism can still lose track of prior failures.  It's pretty hard to eliminate all possible edge cases here, unless perhaps all config/zone commits come with some kind of functional test updates which can be used to query the live running service for the new change's effects after all update operations are complete.

Anyways, to add the missing metadata, I think we have some options (and we can implement them all, since they're all pretty trivial and some might find one mechanism easier to integrate than another):

> * `gdnsdctl stats`: the value of "uptime" does not reset after `gdnsdctl replace`

Yeah - the uptime in the stats tracks that way because `replace` also carries over the stats data to avoid blips in graphs that don't handle low-value rollovers from daemon restarts well.  By carrying over both the stats and the uptime, the two are always meaningful in concert (e.g. "this many reqs have happened in this much time").  It could be more-properly called "stats uptime", but the legacy key "uptime" stuck for compatibility.

We could easily add a new separate output field carrying the uptime of the latest daemon execution, though, and call it "pid uptime" or "process uptime" or something like that (maybe even "config uptime"? lots of name bikeshedding can be done here!).  This would be one solution that could help, although I'm on the fence about putting <1s precision in such a thing, since it encourages thinking this could eliminate races even in the face of parallel operations (it can only make the window smaller!).  Maybe it's of value to do so, though, I donno.  We'd probably want that stamp recorded after all filesystem bits are initially loaded (as opposed to some earlier-valued "when the daemon code started executing" stamp).  In the same spirit, one could also add a timestamp output which updates after each successful `reload-zones` dynamically as well.

[More bikeshedding - maybe the two could be keyed as "config_time" and "zones_time"?]

> * `stat /var/run/gdnsd/control.sock`: the mtime of the control socket does not change after `gdnsdctl replace`

Doing this with e.g. `futimens()` as suggested in your email is also pretty doable and works fine in terms of portability (we already make at least optional use of lots of POSIX.1-2008 -era calls, and we could fall back on legacy lower-precision versions too).  There's probably some subtle things to get right, though, so that e.g. we don't get a spurious and incorrect timestamp update in the case of a fairly late `replace` failure where the new daemon dies and the old continues operation.

> I could teach our init script to write a pidfile but that feels like a fragile hack.

Yes, definitely this would be fragile, but it is a possible solution that would work with some level of reliability under some constraints (especially on independent actors managing things simultaneously).

> Would you accept a patch that makes gdnsd manage a pidfile again? Or is there a better way to do this?

I tend to avoid this path just because it encourages relying on known-racy patterns that read such a pid value.  Having the initscript/system manage such a file is probably less-racy than having gdnsd itself do it though, paradoxically.

**Comment by blblack** [comment]
Closing old stale issues (feel free to re-open if it floats your boat!)
