### ISSUE TITLE
Sibling (In-bailiwick rule of RFC 8499) domain IP records can also be returned along with NS records

### ISSUE THREAD

**Issue by SivaKesava1** [gdnsd/gdnsd#239]
**What would you like to be added**:
[RFC 8499 Page 25](https://www.rfc-editor.org/rfc/rfc8499.html): `Glue records for sibling domains are allowed, but not necessary.  For example, a delegation for "child.example.com"  in "example.com" zone may have a "sibling" name server name  "ns.another.example.com".`

More details can be found here:
https://github.com/coredns/coredns/issues/4377
https://gitlab.isc.org/isc-projects/bind9/-/issues/2384
https://gitlab.isc.org/isc-projects/bind9/-/issues/2385

**Why is this needed**:
Returning the IP records can reduce the number of round-trips by the resolver. All the other leading implementations like PowerDNS, Knot and NSD return these records.

**Comment by blblack** [comment]
As with the related ticket about CNAME chains - this is a design decision that was made intentionally.  We absolutely minimize responses, even if it causes additional queries in practice, because this simplifies and optimizes things in the gdnsd code.  Note that glue which is in-bailiwick for the delegation itself ("in-domain" in RFC 8499) is served, as this is necessary for correct delegation in these situations.
