### ISSUE TITLE
Geoip with Wieghted pluging combination

### ISSUE THREAD

**Issue by YTSre** [gdnsd/gdnsd#92]
Hi

We would love to be able to set "pools" of dc for our gdnsd cluster using the weighted plug and serve these pools using the geoip plugin

The best I got to doing this is setting two "weighted" resources and having them resolve to say ``pool1`.exmaple.com`` and ``pool2.exmaple.com`` and then using the geoip plugin to do DYNC to serve either of those two based on location.

The issue is that we can not do CNAME on our BASE domain ``example.com`` which is the limitation with that 'hack'

Is there any other way to achieve this?

**Comment by blblack** [comment]
Are you trying to do weighting at the top (outer level) and geoip within, or geoip at the outer level and weighting within the pools?  Assuming it's geoip at the outer level, and that you can use IPs rather than CNAMEs to something in some other domain out of your control, you can use weighted as a sub-plugin within each datacenter in the geoip config.

Something like this (loosely based on an example from the testsuite):

```
plugins => {
  geoip => {
    maps => {
      map1 => { ... }
    }
    resources => {
      res1 => {
        map => map1,
        plugin => weighted,
        dcmap => {
          dc1 => {
            lb01 => [192.168.1.111, 20],
            lb02 => [192.168.1.112, 25],
            lb03 => [192.168.1.113, 30],
          }
          dc3 => {
            lb01 => [192.168.2.131, 20],
            lb02 => [192.168.2.132, 25],
            lb03 => [192.168.2.133, 30],
          }
        }
      }
    }
  }
}
```

Then if you reference `foo DYNA geoip!res1` in a zonefile, foo will first do geoip resolution to pick a DC, then do wrr within each DC to choose IPs.  Since it uses DYNA rather than DYNC, it can be used at the root of a zone.

**Comment by YTSre** [comment]
This is absolutely perfect and exactly what I was after!
Sorry I miss that example from the test, Thank you so much!
